### ISSUE TITLE
wotrus certification check failed

### ISSUE THREAD

**Issue by iskycc** [gattjoe/OCSPChecker#34]
All certification of Wotrus CA check failed，such as `wotrus.com`. Please fix.

**Comment by gattjoe** [comment]
Hi,  I have no idea why I didn't get a notification for this. I will look into it.

**Comment by gattjoe** [comment]
Hi @iskycc,

I was able to reproduce the issue. I was running into a timeout while waiting for a response from the WoTrus OCSP Responder.  It works if you change the default request timeout to 10 seconds.  See below:

`foo = ocspchecker.get_ocsp_status("wotrus.com", request_timeout=10)`
`print(foo)`

`['Host: wotrus.com:443', 'OCSP URL: http://ocsp.crlocsp.cn', 'OCSP Status: GOOD']`

Joe
